### ISSUE TITLE
add the ‘hacktoberfest’ topic to the repository to opt the project into Hacktoberfest

### ISSUE THREAD

**Issue by romanlazunin** [ranguli/awesome-flightgear#1]
Hi, would you like to tag the repo with 'hacktoberfest' so opt in project for hacktoberfest contributions please?

According to instructions in [https://hacktoberfest.com/participation/#contributors](https://hacktoberfest.com/participation/#contributors)

Thank you!

**Comment by ranguli** [comment]
Done, great idea thank you!
